NUMPY



Numpy is a general purpose array-processing package in python

In [2]:
import numpy as np

In [3]:
#1d array from a python list
arr1d = np.array([1,2,3,4,5])
arr1d

array([1, 2, 3, 4, 5])

In [4]:
#2d array from a nested python list
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
zeros_arr = np.zeros((3,4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Array attributes

In [6]:
#shape
shape = arr2d.shape
print(shape)

(2, 3)


In [7]:
zeros_arr.shape

(3, 4)

In [9]:
#size (no. of elements we have in our array)
size = arr2d.size
print(size)

6


In [10]:
zeros_arr.size

12

In [11]:
#data type
data_type = arr2d.dtype
print(data_type)

int64


In [12]:
zeros_arr.dtype

dtype('float64')

In [13]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


Array Operations

In [14]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#addition
addition = 2 + arr2d
print(addition)

[[3 4 5]
 [6 7 8]]


In [16]:
#subtraction
subtraction = arr2d - 3
print(subtraction)

[[-2 -1  0]
 [ 1  2  3]]


In [17]:
#Multiplication
multiplication = 4 * arr2d
print(multiplication)

[[ 4  8 12]
 [16 20 24]]


Aggregation Functions

In [18]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#sum
total_sum = arr2d.sum()
print(total_sum)

21


In [20]:
#max
max_val = arr2d.max()
print(max_val)

6


In [21]:
#min
min_val = arr2d.min()
print(min_val)

1


Indexing

In [22]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
#second row
second_row = arr2d[1:,:]
print(second_row)

[[4 5 6]]


In [24]:
#first row
first_row = arr2d[0:1,:]
print(first_row)

[[1 2 3]]


In [25]:
second_row_element = arr2d[1:,1:]
print(second_row_element)

[[5 6]]


In [26]:
first_row_element = arr2d[0:1,0:2]
print(first_row_element)

[[1 2]]


In [27]:
first_row_ = arr2d[0:1,1:]
print(first_row_)

[[2 3]]


In [29]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [30]:
first_row_ = arr2d[0,1:]
print(first_row_)

[2 3]


In [31]:
first_row_ = arr2d[:1,1:]
print(first_row_)

[[2 3]]


In [32]:
first_row_ = arr2d[0,1:]
print(first_row_)

[2 3]


Array Manipulation

In [33]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [34]:
arr2d.shape

(2, 3)

In [35]:
#reshape
reshaped_arr = arr2d.reshape(3,2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [36]:
reshaped_arr1 = arr2d.reshape(1,6)
print(reshaped_arr1)

[[1 2 3 4 5 6]]


In [37]:
#Concatenate Arrays
arr1d = [1,2,3]
concat_arr = np.concat([arr1d,arr1d])
print(concat_arr)

[1 2 3 1 2 3]


In [38]:
#Concatenate Arrays 2
arr1d = np.array([1,2,3])
concat_arr2 = np.concatenate([arr1d,np.array([4,5,6])])
print(concat_arr2)

[1 2 3 4 5 6]


In [39]:
#append
arr1d = np.array([1,2,3])
append_arr = np.append(arr1d,[4,5,6])
print(append_arr)

[1 2 3 4 5 6]


In [41]:
#append to 2 dimensional array
arr2d = np.array([[1,2,3],[4,5,6]]) #row concatination
append_arr1 = np.append(arr2d,[7,8,9])
print(append_arr1)

[1 2 3 4 5 6 7 8 9]


## Question asked

### Can you append a row ([4,5,6]) to the array [1,2,3], so it looks like this [[1,2,3],[4,5,6]] rather than this: [1,2,3,4,5,6]?

### Answer: To achieve that, both arrays need to be two-dimensional arrays.

In [42]:
#Answer to question asked
arr1d = np.array([[1,2,3]])
concat_arr2 = np.concatenate([arr1d,np.array([[4,5,6]])])
print(concat_arr2)

[[1 2 3]
 [4 5 6]]


## Broadcasting

In [46]:
#broadcasting  #allows operations between arrays of different shapes or dimensions
a = np.array([1,2,3])
b = 4
print(a+b)

[5 6 7]


In [48]:
a = np.array([1,2,3])
b = 6
print(a*b)

[ 6 12 18]


In [49]:
a = np.array([1,2,3])
print(4 + a)

[5 6 7]


## Random Number Generation

In [52]:
random_numbers = np.random.rand(3,3)
print(random_numbers)

[[0.65036278 0.97126136 0.45497434]
 [0.22917262 0.13621398 0.92843525]
 [0.14482859 0.82862052 0.66448202]]


In [53]:
random_numbers = np.random.rand(4,6)
print(random_numbers)

[[0.33891712 0.86654042 0.94805588 0.36695448 0.52965997 0.19100011]
 [0.18308478 0.2009448  0.57285136 0.74326336 0.27520011 0.01230444]
 [0.13129811 0.23890089 0.87631677 0.65114266 0.72047262 0.02123571]
 [0.07561956 0.00790205 0.35641607 0.15389904 0.37127468 0.05679904]]


In [96]:
random_numbers_ = np.random.randint(0,100,6)
print(random_numbers_)

[ 3 52 96 91  1 51]


In [95]:
random_numbers_ = np.random.randint(0,100,6).reshape(3,2) #3 rows 2 columns
print(random_numbers_)

[[74  6]
 [21 34]
 [29 93]]


In [97]:
random_numbers1 = np.random.randn(4, 7) #generates random numbers for a normal distribution
print(random_numbers1)

[[ 0.69692179  1.04161882  1.20725665  1.64824871 -0.15893794 -1.2922022
  -0.18155024]
 [ 0.23589814 -0.03623601  1.1382575  -0.73068303  0.48884724  0.45845295
  -0.87186649]
 [-1.73521328 -0.67425725 -0.62394132 -0.19944078 -0.62089625 -0.80563239
  -1.50156399]
 [ 0.21752065 -1.6935174  -0.34316338 -0.23591089  0.65767429 -0.09284761
   0.85247087]]


In [99]:
items = np.array (["A", "B", "C", "D"])
items

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [100]:
random_numbers2 = np.random.choice(items, 3)
print(random_numbers2)

['D' 'D' 'C']


## Linear Algebra

In [101]:
# Matrix Addition
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A, B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [60]:
A

array([[1, 2],
       [3, 4]])

In [62]:
B

array([[5, 6],
       [7, 8]])

In [63]:
print(A + B)

[[ 6  8]
 [10 12]]


In [102]:
#Matrix Subtraction
print(A - B)

[[-4 -4]
 [-4 -4]]


In [103]:
#Matrix Multiplication (Element-wise multiplication)
print(A * B)

[[ 5 12]
 [21 32]]


In [105]:
#Matrix Multiplication
print(A @ B)

[[19 22]
 [43 50]]


In [106]:
result = np.matmul(A,B)
print(result)

[[19 22]
 [43 50]]


In [68]:
#Normal Matrix Multiplication
F = np.dot(A,B)
print(F)

[[19 22]
 [43 50]]


In [69]:
#Matrix Multiplication (Column-wise)
print(A * B)

[[ 5 12]
 [21 32]]


In [70]:
# Standard Matrix multiplication
F = np.dot(A,B)
print(F)

[[19 22]
 [43 50]]


In [71]:
A

array([[1, 2],
       [3, 4]])

In [109]:
#Transpose of a matrix
transpose_A = np.transpose(A)
print(transpose_A)

[[1 3]
 [2 4]]


In [73]:
#Transpose of a matrix
transpose_B = np.transpose(B)
print(transpose_B)

[[5 7]
 [6 8]]


In [74]:
A

array([[1, 2],
       [3, 4]])

In [107]:
#Inverse of a matrix
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [108]:
#Inverse of a matrix
B_inv = np.linalg.inv(B)
print(B_inv)

[[-4.   3. ]
 [ 3.5 -2.5]]


In [110]:
#identity Matrix
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [111]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
B

array([[5, 6],
       [7, 8]])

In [112]:
#determinant of a matrix #a single numerical value computed from a square matrix
determinant = np.linalg.det(B)
print(int(determinant))

-2


[a b
 c  d]
 det a = [ad- bc]


## Delete elements in an array

In [81]:
arr = np.array([1,2,3,4,5]) #identify the position of the element you want to delete
arr_deleted = np.delete(arr,2)
print(arr_deleted)

[1 2 4 5]


In [82]:
arr_deleted = np.delete(arr,4)
print(arr_deleted)

[1 2 3 4]


In [115]:
club_arr = np.array(['Madrid','Barcelona','Arsenal','Dortmund','PSG','Mancity'])
arr_deleted = np.delete(club_arr,[1,2])
print(arr_deleted)

['Madrid' 'Dortmund' 'PSG' 'Mancity']


In [116]:
arr = np.array([1,2,3,4,5])
m = arr != 5
new_arr = arr[m]
print(new_arr)

[1 2 3 4]


### To make sure that the elements that are removed in arr_deleted are also deleted in club_arr

In [117]:
club_arr = np.array(['Madrid','Barcelona','Arsenal','Dortmund','PSG','Mancity'])
arr_deleted = np.delete(club_arr,[1,2])
club_arr = arr_deleted
print(club_arr)


['Madrid' 'Dortmund' 'PSG' 'Mancity']


## Statistical Functions

In [119]:
arr = np.array([1,2,3,4,5,6])


In [120]:
#mean
arr_mean = np.mean(arr)
print(arr_mean)

3.5


In [121]:
#median
arr_median = np.median(arr)
print(arr_median)

3.5


In [90]:
arr_1 = np.array([1,2,3,4,5,6])

In [91]:
arr1_median = np.median(arr_1)
print(arr1_median)

3.5


In [122]:
#Mode : numpy does not have the mode method, so scipy can be used
arr_ = np.array([1,2,2,3,4,5,6])
from scipy import stats
arr_mode = stats.mode(arr_,keepdims = False)
print(arr_mode)

ModeResult(mode=np.int64(2), count=np.int64(2))


In [123]:
#standard deviation
arr_std = np.std(arr)
print(arr_std)

1.707825127659933
